{ config, pkgs, ... }:

{
	# Writes ~/.config/hypr/hypr-binds.lua
	# hyprland.lua itself is autogenerated and not managed by Home Manager here -
	# add this single line to it (near/after the existing KEYBINDINGS section)
	# so these binds load and override the stock ones:
	#   require("hypr-binds")
	xdg.configFile."hypr/hypr-binds.lua".source = ./hypr-binds.lua;
}
